// seed/chapterData.rucamden.mjs
export default [
  {
    name: "Alpha Chi Rho (Rutgers–Camden)",
    letters: "Alpha Phi Eta",
    organization: "Alpha Chi Rho Fraternity",
    crestUrl: "",
    about: "Active IFC fraternity at Rutgers University–Camden.",
    establishedDate: null,
    isActive: true,
  },
  {
    name: "Alpha Kappa Alpha – Pi Epsilon (Rutgers–Camden)",
    letters: "PI EPSILON",
    organization: "Alpha Kappa Alpha Sorority, Inc.",
    crestUrl: "",
    about: "NPHC sorority; Pi Epsilon Chapter chartered April 28, 1990 at Rutgers–Camden.",
    establishedDate: new Date("1990-04-28"),
    isActive: true,
  }, 
  {
    name: "Delta Phi Epsilon (Rutgers–Camden)",
    letters: "",
    organization: "Delta Phi Epsilon Sorority",
    crestUrl: "",
    about: "NPC sorority with an active chapter at Rutgers–Camden.",
    establishedDate: null,
    isActive: true,
  },
  {
    name: "Lambda Sigma Upsilon (Rutgers–Camden)",
    letters: "Somali",
    organization: "Lambda Sigma Upsilon Latino Fraternity, Inc.",
    crestUrl: "",
    about: "NALFO fraternity; active chapter at Rutgers–Camden.",
    establishedDate: null,
    isActive: true,
  },
  {
    name: "Lambda Tau Omega (Rutgers–Camden)",
    letters: "Chi",
    organization: "Lambda Tau Omega Sorority, Inc.",
    crestUrl: "",
    about: "Multicultural sorority (LTO “Mermaids”) active at Rutgers–Camden.",
    establishedDate: null,
    isActive: true,
  },
  {
    name: "Lambda Theta Alpha (Rutgers–Camden)",
    letters: "Rho",
    organization: "Lambda Theta Alpha Latin Sorority, Inc.",
    crestUrl: "",
    about: "Latin sorority (LTA) active at Rutgers–Camden.",
    establishedDate: null,
    isActive: true,
  },
  {
    name: "Mu Sigma Upsilon (Rutgers–Camden)",
    letters: "",
    organization: "Mu Sigma Upsilon Sorority, Inc.",
    crestUrl: "",
    about: "Multicultural sorority (MSU) active at Rutgers–Camden.",
    establishedDate: null,
    isActive: true,
  },
  {
    name: "Phi Beta Sigma (Rutgers–Camden)",
    letters: "",
    organization: "Phi Beta Sigma Fraternity, Inc.",
    crestUrl: "",
    about: "NPHC fraternity (Sigmas) active at Rutgers–Camden.",
    establishedDate: null,
    isActive: true,
  },
  {
    name: "Sigma Delta Tau (Rutgers–Camden)",
    letters: "",
    organization: "Sigma Delta Tau Sorority",
    crestUrl: "",
    about: "NPC sorority active at Rutgers–Camden.",
    establishedDate: null,
    isActive: true,
  },
  {
    name: "Tau Epsilon Phi – Sigma Epsilon (Rutgers–Camden)",
    letters: "SIGMA EPSILON",
    organization: "Tau Epsilon Phi Fraternity",
    crestUrl: "",
    about: "IFC fraternity; local chapter founded in 1967 at Rutgers–Camden.",
    establishedDate: new Date("1967-01-01"),
    isActive: true,
  }, 
  {
    name: "Tau Kappa Epsilon – Pi Chi (Rutgers–Camden)",
    letters: "PI CHI",
    organization: "Tau Kappa Epsilon Fraternity",
    crestUrl: "",
    about: "IFC fraternity; Pi Chi Chapter at Rutgers–Camden.",
    establishedDate: null,
    isActive: true,
  }, 
  {
    name: "Zeta Phi Beta – Theta Omicron (Rutgers–Camden)",
    letters: "THETA OMICRON",
    organization: "Zeta Phi Beta Sorority, Inc.",
    crestUrl: "",
    about: "NPHC sorority; Theta Omicron Chapter chartered April 19, 1993 at Rutgers–Camden.",
    establishedDate: new Date("1993-04-19"),
    isActive: true,
  }, 
];
