export default [
  {
    name: "Alpha Chi Rho",
    letters: "ΑΧΡ",
    crestUrl: "",
    about: "IFC fraternity with presence at Rutgers University–Camden.",
    establishedDate: new Date("1895-06-04"),
    isActive: true,
  },
  {
    name: "Alpha Kappa Alpha Sorority, Inc.",
    letters: "ΑΚΑ",
    crestUrl: "",
    about: "NPHC sorority; Pi Epsilon Chapter at Rutgers–Camden.",
    establishedDate: new Date("1908-01-15"),
    isActive: true,
  },
  {
    name: "Delta Phi Epsilon",
    letters: "ΔΦΕ",
    crestUrl: "",
    about: "NPC sorority with an active chapter at Rutgers–Camden.",
    establishedDate: new Date("1917-03-17"),
    isActive: true,
  },
  {
    name: "Lambda Sigma Upsilon Latino Fraternity, Inc.",
    letters: "ΛΣΥ",
    crestUrl: "",
    about: "NALFO fraternity; active chapter at Rutgers–Camden.",
    establishedDate: new Date("1979-04-05"),
    isActive: true,
  },
  {
    name: "Lambda Tau Omega Sorority, Inc.",
    letters: "ΛΤΩ",
    crestUrl: "",
    about: "Multicultural sorority (LTO “Mermaids”) active at Rutgers–Camden.",
    establishedDate: new Date("1988-10-09"), 
    isActive: true,
  },
  {
    name: "Lambda Theta Alpha Latin Sorority, Inc.",
    letters: "ΛΘΑ",
    crestUrl: "",
    about: "Latin sorority (LTA) active at Rutgers–Camden.",
    establishedDate: new Date("1975-12-01"),
    isActive: true,
  },
  {
    name: "Mu Sigma Upsilon Sorority, Inc.",
    letters: "ΜΣΥ",
    crestUrl: "",
    about: "Multicultural sorority (MSU) active at Rutgers–Camden.",
    establishedDate: new Date("1981-11-21"),
    isActive: true,
  },
  {
    name: "Phi Beta Sigma Fraternity, Inc.",
    letters: "ΦΒΣ",
    crestUrl: "",
    about: "NPHC fraternity (Sigmas) active at Rutgers–Camden.",
    establishedDate: new Date("1914-01-09"),
    isActive: true,
  },
  {
    name: "Sigma Delta Tau",
    letters: "ΣΔΤ",
    crestUrl: "",
    about: "NPC sorority active at Rutgers–Camden.",
    establishedDate: new Date("1917-03-25"),
    isActive: true,
  },
  {
    name: "Tau Epsilon Phi",
    letters: "ΤΕΦ",
    crestUrl: "",
    about: "IFC fraternity; local chapter founded in 1967 at Rutgers–Camden.",
    establishedDate: new Date("1910-10-10"),
    isActive: true,
  },
  {
    name: "Tau Kappa Epsilon",
    letters: "ΤΚΕ",
    crestUrl: "",
    about: "IFC fraternity; Pi Chi Chapter at Rutgers–Camden.",
    establishedDate: new Date("1899-01-10"),
    isActive: true,
  },
  {
    name: "Zeta Phi Beta Sorority, Inc.",
    letters: "ΖΦΒ",
    crestUrl: "",
    about: "NPHC sorority; Theta Omicron Chapter at Rutgers–Camden.",
    establishedDate: new Date("1920-01-16"),
    isActive: true,
  },
];