export default [
  {
    authorEmail: "ashley@example.com",
    organizationName: "Lambda Tau Omega Sorority, Inc.",
    text: "Kicking off the semester with a community service drive this Saturday. All are welcome 💙🐚",
    picture: "",
    likeCount: 3,
    createdAt: new Date("2025-09-01T14:10:00Z"),
  },
  {
    authorEmail: "peter@example.com",
    organizationName: "Alpha Chi Rho",
    text: "IFC meet & greet tonight at the student center. Come say hi!",
    picture: "",
    likeCount: 2,
    createdAt: new Date("2025-09-03T22:30:00Z"),
  },
  {
    authorEmail: "maria@example.com",
    organizationName: "Lambda Theta Alpha Latin Sorority, Inc.",
    text: "Study night in the library. Open to everyone! Bring a friend and your laptop 📚",
    picture: "",
    likeCount: 5,
    createdAt: new Date("2025-09-05T18:45:00Z"),
  },
  {
    authorEmail: "jordan@example.com",
    organizationName: "Tau Kappa Epsilon",
    text: "Congrats to our intramural soccer team for last night’s W! ⚽️",
    picture: "",
    likeCount: 4,
    createdAt: new Date("2025-09-07T03:15:00Z"),
  },
  {
    authorEmail: "tina@example.com",
    organizationName: "Zeta Phi Beta Sorority, Inc.",
    text: "Scholarship applications open next week. Details coming soon.",
    picture: "",
    likeCount: 7,
    createdAt: new Date("2025-09-08T16:05:00Z"),
  },
  {
    authorEmail: "leo@example.com",
    organizationName: "Phi Beta Sigma Fraternity, Inc.",
    text: "Blue & White cookout this Friday on the quad! 🍔🌭",
    picture: "",
    likeCount: 6,
    createdAt: new Date("2025-09-10T19:00:00Z"),
  },
  {
    authorEmail: "nina@example.com",
    organizationName: "Mu Sigma Upsilon Sorority, Inc.",
    text: "Thanks to everyone who donated to our backpack drive. We hit our goal! 🎒",
    picture: "",
    likeCount: 9,
    createdAt: new Date("2025-09-12T13:25:00Z"),
  },
  {
    authorEmail: "sam@example.com",
    organizationName: "Tau Epsilon Phi",
    text: "Open mic night collab with LTA next Thursday DM to perform 🎤",
    picture: "",
    likeCount: 1,
    createdAt: new Date("2025-09-13T21:40:00Z"),
  },
  {
    authorEmail: "vivian@example.com",
    organizationName: "Sigma Delta Tau",
    text: "Big/Little reveal this weekend! 💫",
    picture: "",
    likeCount: 8,
    createdAt: new Date("2025-09-15T15:55:00Z"),
  },
  {
    authorEmail: "darius@example.com",
    organizationName: "Lambda Sigma Upsilon Latino Fraternity, Inc.",
    text: "Volunteering at the community garden this Sunday. Join us 🌱",
    picture: "",
    likeCount: 2,
    createdAt: new Date("2025-09-17T11:10:00Z"),
  },
  {
    authorEmail: "karen@example.com",
    organizationName: "Delta Phi Epsilon",
    text: "Mental health awareness table today outside the union 💜",
    picture: "",
    likeCount: 10,
    createdAt: new Date("2025-09-18T17:20:00Z"),
  },
  {
    authorEmail: "mike@example.com",
    organizationName: "Alpha Kappa Alpha Sorority, Inc.",
    text: "Panel on career prep and internships next Monday. RSVP link in bio.",
    picture: "",
    likeCount: 3,
    createdAt: new Date("2025-09-20T20:05:00Z"),
  },
];